"""init

Revision ID: be751c2087e1
Revises: 
Create Date: 2025-01-25 15:12:00.145449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'be751c2087e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_chats',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=False),
    sa.Column('chat_type', sa.Enum('PRIVATE', 'CHANNEL', 'SUPERGROUP', 'GROUP', name='chattype'), nullable=False),
    sa.Column('settings', mysql.JSON(), nullable=False),
    sa.Column('last_init', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', 'id')
    )
    op.create_table('telegram_users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id', 'id')
    )
    op.create_table('telegram_user_chat_association',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('MEMBER', 'ADMIN', 'OWNER', 'BANNED', name='userrole'), nullable=False),
    sa.Column('warn_count', sa.Integer(), nullable=False),
    sa.Column('ban_expires', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('mute_expires', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('mute_metadata', mysql.JSON(), nullable=False),
    sa.Column('ban_metadata', mysql.JSON(), nullable=False),
    sa.Column('privileges', mysql.JSON(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['telegram_chats.telegram_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['telegram_users.telegram_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'chat_id', 'id'),
    sa.UniqueConstraint('user_id', 'chat_id', name='uq_user_chat')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_user_chat_association')
    op.drop_table('telegram_users')
    op.drop_table('telegram_chats')
    # ### end Alembic commands ###
